### ISSUE TITLE
Clarification on what this module does

### ISSUE THREAD

**Issue by SyntaxPolice** [BradJonesLLC/simplesamlphp-openid-connect#5]
Greetings! I'd recommend adding a little tiny bit of info to the README to clarify what the module does.

e.g.
- Does it enable SimpleSamlPHP to operate as an OIDC IDP?
- Does it act as the RP: an auth source for a 3rd party OIDC IDP (e.g. you can log into your SAML IDP with Twitter)
- Other?

**Comment by bradjones1** [comment]
Thanks. Will consider in fixing #2.
