### ISSUE TITLE
simpleSAMLphp namespace warnings

### ISSUE THREAD

**Issue by mrvanes** [BradJonesLLC/simplesamlphp-openid-connect#9]
We've recently bumped into simpleSAMLphp namespace warnings and a deprecated OAuth2.php include. Are you still maintaining the code, or should we fork and maintain our own?

Here's what we changed:
https://github.com/BradJonesLLC/simplesamlphp-module-openidconnect/compare/master...SURFscz:master

**Comment by bradjones1** [comment]
@mrvanes Thanks, and yes I'm still using this and interested in maintaining a mainline implementation instead of requiring users to fork... could you file a PR that doesn't change the project name and removes the unnecessary code instead of commenting it out?

**Comment by bradjones1** [comment]
@mrvanes Thanks!
